const PokemonDetailStyles = {
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: "1rem",
  },
  modal: {
    background: "#fff",
    borderRadius: "16px",
    padding: "2rem",
    maxWidth: "500px",
    width: "100%",
    maxHeight: "90vh",
    overflowY: "auto",
    boxShadow: "0 10px 25px rgba(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    animation: "fadeIn 0.3s ease",
  },
  title: {
    textTransform: "capitalize",
    textAlign: "center",
    marginBottom: "1rem",
    fontSize: "1.8rem",
    fontWeight: "bold",
  },
  image: {
    width: "180px",
    height: "180px",
    marginBottom: "1rem",
  },
  section: {
    width: "100%",
    marginBottom: "1rem",
  },
  label: {
    fontWeight: "bold",
    marginBottom: "0.5rem",
  },
  typesContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "0.5rem",
    flexWrap: "wrap",
    marginBottom: "1rem",
  },
  typeBadge: {
    background: "#e6e6e6",
    borderRadius: "8px",
    padding: "0.3rem 0.6rem",
    textTransform: "capitalize",
    fontSize: "0.85rem",
  },
  statsList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  statItem: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "0.25rem",
  },
  description: {
    fontStyle: "italic",
    lineHeight: 1.4,
    textAlign: "center",
    marginBottom: "1rem",
  },
  closeButton: {
    padding: "0.5rem 1.2rem",
    borderRadius: "8px",
    border: "none",
    background: "#333",
    color: "#fff",
    cursor: "pointer",
    marginTop: "1rem",
    transition: "background 0.2s ease",
  },
};

export default PokemonDetailStyles;
